### ISSUE TITLE
1.3.3 does not remember/restore

### ISSUE THREAD

**Issue by m0rg5** [iina/iina#4662]
**System and IINA version:**
- macOS 13.6, 2020 m1 Macbook Air
- IINA 1.3.3

**Expected behavior:**
Key-bindings/saved keystrokes are saved/restored on re-open. 

**Actual behavior:**
No custom config files are present in key-bindings/saved keystrokes. 

When I try to restore a config file I get a 'cannot create . .', file present error - yet no config is shown in list.
<br>

<details>
<summary><b>mpv log:</b></summary>

```
Enabled but no log is created.
```
</details>

<br>

**Steps to reproduce:**
Quit, reopen.

**How often does this happen?**
Every time

**Comment by low-batt** [comment]
Did not reproduce for me.

I tried the following:
- I created a key binding configuration file named `issue-4662.conf`
- I started IINA
- I clicked on  `Settings…` under the `IINA` menu
- On the left side of the settings panel I clicked on `Key Bindings`
- I clicked on the `Import an existing config file`
- I selected the `issue-4662.conf` file I created and imported it
- IINA showed the imported file in the settings panel
- I restarted IINA
- I went back to the key binding settings
- The new key bindings were still present and selected

Checking the directory where IINA stores user configured key bindings shows IINA saved the imported file:
```text
low-batt@gag ~$ cd Library/Application\ Support/com.colliderli.iina/input_conf/
low-batt@gag input_conf$ ls -la issue-4662.conf
-rw-r--r--@ 1 low-batt  staff  1966 Mar 17  2023 issue-4662.conf
low-batt@gag input_conf$ 
```

Possibly there is something in the key binding file you are trying to import that is causing a problem. Can you post the file that fails to import?

**Comment by m0rg5** [comment]
This is not about importing configs, it is about any custom configs - duplicating existing iina/creating new, it does not show any user config upon restart.

**Comment by low-batt** [comment]
I'm still having trouble reproducing this one. On this:
> When I try to restore a config file I get a 'cannot create . .', file present error - yet no config is shown in list.

What is the full error message?

Here is what I did to try and reproduce the problem this time. I cleared all my additional key bindings so that I only had the 4 default ones. Then I duplicated the `IINA Default` bindings and changed the commands associated with the arrow keys:

![issue-4662](https://github.com/iina/iina/assets/86170219/b9b4b44f-edbf-4a89-9a39-dac148ddf70a)

All went fine. The new key bindings were still working after IINA was restarted.

This test was performed under macOS Ventura 13.5.2.

@svobs Have you experienced such a failure?

**Comment by svobs** [comment]
Check that your input config directory is still there and has correct permissions. It's located at `/Users/{your_user_name}/Library/Application\ Support/com.colliderli.iina/input_conf/`. Or you can just open IINA and click on `Show the config file in Finder`. Make sure it is able to open a window in the Finder to a folder called `input_conf`. You should see any `.conf` files that you have created or imported in that folder. You won't see the 4 built-in configs there (the ones with the lock), so if you haven't made any of your own, the folder may be empty.

If the folder exists and is empty, make sure you have read & write permissions to that folder.

Also check to see if there is already a file in that folder with the same name as the one you're trying to import. IINA stores its own internal list of configs which it needs to update for everything to work properly, so you can't just drag & drop files into that folder for them to be seen by IINA. You need to use the Key Bindings settings as shown above. So make sure the file names in that folder match the list of user configs in the IINA settings (after subtracting the `.conf` file extensions).

**Comment by low-batt** [comment]
To see the internal list of user created key bindings @svobs mentioned enter the following command in [Terminal](https://support.apple.com/guide/terminal/welcome/mac):
```text
defaults read com.colliderli.iina inputConfigs
```

This is what that looks like when I run it right now after I configured a custom key binding named `step`:
```text
low-batt@gag ~$ defaults read com.colliderli.iina inputConfigs
{
    step = "/Users/low-batt/Library/Application Support/com.colliderli.iina/input_conf/step.conf";
}
low-batt@gag ~$ 
```

That file is present in my `input_conf` directory:
```text
low-batt@gag ~$ ls -l Library/Application\ Support/com.colliderli.iina/input_conf/
total 8
-rw-r--r--@ 1 low-batt  staff  1978 Oct 22 19:37 step.conf
low-batt@gag ~$ 
```

**Comment by m0rg5** [comment]
Hi, thanks for detail.

Yes, input-conf/ has all the profiles I created, I'd prior checked that and should have said above. I just checked and new ones are indeed being added there, and still don't appear on iina restart.

![image](https://github.com/iina/iina/assets/8669538/61a6dfdb-be69-456e-bf43-b45d315d8c07)

I get:

```
defaults read com.colliderli.iina inputConfigs
2023-10-24 00:17:57.533 defaults[43606:1590631]
The domain/default pair of (com.colliderli.iina, inputConfigs) does not exist
```

**Comment by svobs** [comment]
> Yes, input-conf/ has all the profiles I created, I'd prior checked that and should have said above. I just checked and new ones are indeed being added there, and still don't appear on iina restart.

Ah, are you launching IINA from the disk image (dmg) file? You need to drag and drop IINA into your `Applications` folder and then launch it from there, otherwise your settings will get blown away after you quit.

If that's not it, next best guess is that something is wrong with your Mac's `Preferences` directory, or you have installed security software which deletes settings which aren't specifically allowed, or some other thing like that.

Check that the file `/Users/mb/Library/Preferences/com.colliderli.iina.plist` exists. What happens when you try `ls -l /Users/mb/Library/Preferences/com.colliderli.iina.plist` from Terminal? This is what I get for my user, `msvoboda`:
```
-rw-------@ 1 msvoboda  staff  764202 Oct 23 11:33 /Users/msvoboda/Library/Preferences/com.colliderli.iina.plist
```

**Comment by low-batt** [comment]
Leaving off the key `inputConfigs` in the command shown above and just executing:
```text
defaults read com.colliderli.iina
```

Will show you all of IINA's settings. If that command reports an error then we are worried that the property list has somehow become corrupted.

You should be able to change a setting in IINA and see it reflected in the output of that command.

**Comment by m0rg5** [comment]
Yes, it's in /Applications/ ;)

> Check that the file `/Users/mb/Library/Preferences/com.colliderli.iina.plist` exists. What happens when you try `ls -l /Users/mb/Library/Preferences/com.colliderli.iina.plist` from Terminal? 

```
mb@macm1 ~ % ls -l /Users/mb/Library/Preferences/com.colliderli.iina.plist
lrwxr-xr-x@ 1 mb  staff  84  9 Oct 11:33 /Users/mb/Library/Preferences/com.colliderli.iina.plist -> /Users/mb/Google Drive/My Drive/Mackup/Library/Preferences/com.colliderli.iina.plist
```

I've actually uninstalled Mackup, and manually removed that Mackup dir, so something weird going on here.
Is GDrive behind this?

I get:

```
mb@macm1 ~ % defaults read com.colliderli.iina
2023-10-25 01:15:56.104 defaults[56686:2015537] 
Domain com.colliderli.iina does not exist
```

**Comment by m0rg5** [comment]
I've got weird stuff going on with permission it seems, and Brew (which I installed iina through).

Discovered Brew wasn't working, got below erros after 2nd Brew reinstall (it actually worked immediately after 1st reinstall):

```
- Run brew help to get started
- Further documentation:
    https://docs.brew.sh

mb@macm1 ~ % brew doctor
zsh: command not found: brew
mb@macm1 ~ % brew help
zsh: command not found: brew
```

I've tried: 
`sudo diskutil resetUserPermissions / $(id -u)
`
Still have issues

**Comment by low-batt** [comment]
This:
```text
mb@macm1 ~ % defaults read com.colliderli.iina
2023-10-25 01:15:56.104 defaults[56686:2015537] 
Domain com.colliderli.iina does not exist
```

Is **BAD**. IINA is using the macOS [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults) system for storing settings. The `defaults` command is a part of that system.  This error means macOS can't find IINA's settings.

The property list is present, but it is not a file! Instead it is a link to the cloud:
```text
mb@macm1 ~ % ls -l /Users/mb/Library/Preferences/com.colliderli.iina.plist
lrwxr-xr-x@ 1 mb  staff  84  9 Oct 11:33 /Users/mb/Library/Preferences/com.colliderli.iina.plist -> /Users/mb/Google Drive/My Drive/Mackup/Library/Preferences/com.colliderli.iina.plist
```

My _own personal opinion_ is that this is an extremely bad idea. With software there are things you can do, but shouldn't do. If you violate the vision of the designers of macOS, even if it seems like it should be safe to do, you have taken yourself outside of what Apple tests. As it is there are issues with macOS quality.

Based on the filename, the file containing the property list that was here has been deleted and replaced with a link to a file on `Google Drive`. I've seen this technique used to share application settings across devices. The trouble with this method for doing that is that when you do not have internet access all of your application settings are lost.

In the case of applications that have settings that correspond to files this technique makes it more likely that the property list can get out of sync with the external files. For example if the application adds a file and then can't adjust the property list to reflect that due to a momentary glitch writing to the cloud.

Based on the pathname the link was added by [Mackup](https://github.com/lra/mackup). From the README:
> You can revert all your files to their original state.
> ```bash
> # Just run this
> mackup uninstall
> ```
> This will remove the symlinks and copy back the files from the Mackup folder in Dropbox to their original places in your home. The Mackup folder and the files in it stay put, so that any other computer also running Mackup is unaffected.

Did you run that command before uninstalling?

I'm not thinking there are problems with permissions. I'm thinking there are links to missing critical files.

If the uninstall was not run, it might be possible to reinstall `Mackup`, configure it like it was and then run uninstall. **CAUTION** I have never heard of `Mackup` before. Might be better to ask that project how to proceed.

**Comment by svobs** [comment]
Interesting to learn how MacOS handles `.plist` files which have been replaced with broken symlinks. But sort of makes sense. An application's prefs are stored first and foremost in RAM like an in-memory store, with occasional writes to the `.plist` file for permanent storage.

@m0rg5 if you can't find your old backup or it's not worth bothering to restore it, you can just delete the symlink, and then the next time you launch IINA it should build you a new `.plist` file based on the default prefs. You can either run this in Terminal:
```
unlink /Users/mb/Library/Preferences/com.colliderli.iina.plist
```
Or just get to it in Finder and throw it in the Trash. And move your key binding files out of IINA's `input_conf`, then re-import them through IINA's Settings window.

_Although_ it sounds like you're going to have a lot more applications impacted than just IINA, and it would be smarter to set things up again so you can do a proper uninstall, if possible.

**Comment by m0rg5** [comment]
Firstly, thanks so much for all the attention and help!

I've since deleted iina and started again, the plist is registering now, yet this has brought up all this other junk!

I ran `brew uninstall mackup` - (maybe there's an issue in Brew?) before I showed that it still registered the file as in the cloud. 

I have GDrive syncing only the following, and place things in Documents/ that I want synced.
![image](https://github.com/iina/iina/assets/8669538/8d40b232-995c-4457-89f1-83f4f7b17bea)

So Mackup created the symlinks to Documents, that ended up linked to the cloud?
Bizarre - I had no idea it was doing this with files, I thought it was simply creating a local backup and I was then syncing Documents/ to GDrive - but I'm still not clear whate exactly has caused this.
CONFUSING!

**Comment by m0rg5** [comment]
I don't expect you guys to have the answers, will reach out to mackup, seems like [this issue](https://github.com/lra/mackup/issues/1924)? 

But to keep you in the loop:

I just `brew install mackup` again (along with crap-ton of dependencies) so I could `mackup uninstall`, and got:
```
mackup uninstall
/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/docopt.py:165: SyntaxWarning: invalid escape sequence '\S'
  name = re.findall('(<\S*?>)', source)[0]
/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/docopt.py:166: SyntaxWarning: invalid escape sequence '\['
  value = re.findall('\[default: (.*)\]', source, flags=re.I)
/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/docopt.py:207: SyntaxWarning: invalid escape sequence '\['
  matched = re.findall('\[default: (.*)\]', description, flags=re.I)
/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/docopt.py:456: SyntaxWarning: invalid escape sequence '\S'
  split = re.split('\n *(<\S+?>|-\S+?)', doc)[1:]
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/main.py", line 66, in main
    mckp = Mackup()
           ^^^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
                   ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 46, in __init__
    self._parser = self._setup_parser(filename)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.37/libexec/lib/python3.12/site-packages/mackup/config.py", line 150, in _setup_parser
    parser = configparser.SafeConfigParser(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

**Comment by low-batt** [comment]
I think that is a different Mackup issue, this one: https://github.com/lra/mackup/issues/1948

**Comment by low-batt** [comment]
On this:
>So Mackup created the symlinks to Documents, that ended up linked to the cloud?
Bizarre - I had no idea it was doing this with files, I thought it was simply creating a local backup and I was then syncing Documents/ to GDrive - but I'm still not clear whate exactly has caused this.

That may be the case, which should allow you to keep working when the cloud isn't available, but raises questions about how conflicting changes are resolved. Like if config changes are made on a device that was offline and before that device has a chance to sync, changes were made on another device that updated the cloud.

In the case at hand if IINA's property list was sync'd to another device, that would only work if the key binding files were also linked to GDrive and also sync'd to the other device. Otherwise the property list on another device would refer to files that are missing.

The incident that made me have such a negative view on such systems was a problem with a Windows machine I was asked to look into. That PC had linked configuration files and did have local copies, but was freezing and running slow because the cloud was not available for syncing.

I asked some other software engineers their views on syncing configuration files to the cloud like this, Some were doing this successfully and had good things to say about this technique. I may need to rethink my view on this. But as this current issue shows if anything goes wrong with such systems it can cause severe odd problems.

Hope you are able to sort this out and get your Mac working well again soon.
